### ISSUE TITLE
Include the tutorial in the build system

### ISSUE THREAD

**Issue by nojhan** [nojhan/paradiseo#60]
Tutorials are not build with examples and tests, which leads to inconsistencies with API changes.

**Comment by Scicomath** [comment]
You can build tutorials if you set CMake option `ENABLE_CMAKE_EXAMPLE=true`, e.g.:
`cmake -DENABLE_CMAKE_EXAMPLE=true ..`

**Comment by nojhan** [comment]
Forgot to close, thanks for spotting it!
