### ISSUE TITLE
Correct location for contributions

### ISSUE THREAD

**Issue by filipesaraiva** [nojhan/paradiseo#64]
Just a doubt, this Paradiseo Github repository has a lot of contributions but there is an Paradiseo repository at [INRIA Gitlab](https://gitlab.inria.fr/paradiseo/paradiseo).

I would like to know if this github repository is the 'correct' place for contributions and/or if the repository at INRIA is just like a mirror.

Maybe this info could be more clear at README and project website.

All the best!

**Comment by jdreo** [comment]
TL,DR: pick the one you prefer.

I don't have admin rights on the INRIA repository anymore so I work on Github, now. But I try to mirror commits on both repositories, so using one or the other should just be a matter of taste at the end.
Github tends to be edgier (as for my own developments, but it's possible that someone else will commit on INRIA's Gitlab, which will be backported on Github at the end, anyway) and I tend to react more rapidly on Github than on INRIA's Gitlab, as of now. Of course, you may prefer one interface or the other.
